import Vue from 'vue'
import Vuex from 'vuex'
Vue.use(Vuex)

const picAd={
	state: {
		picAdNum:0,
		test1: "a",
		test2: "b",
		test3: "c",
		test4: "d",
	},
}
const codeType={
	state: {
		type:null
	},
	mutations:{
		changeType(state,type){
			//溯源码
			if(type=='a'){
				state.type=0
				return
			};
			//防伪码
			if(type=='b'){
				state.type=1
				return
			}
		}
	}
}
const gameRule={
	state: {
		ruleId:null
	},
	mutations: {
		getId(state,type){
			if(type==='add'){
				state.ruleId=null
			}else{
				state.ruleId=type;
			}
		}
	}
}
const banner1={
	state:{
		isNew:true,
		vendorId:null,
		actionId:null,
		data:{
			picAd1:false,
			showModule:false,
			picNum:2,
			bannerPic:[
				{src:null,img:'https://ym-a.top/wx/img/tu2.jpg',address:'func/you.html'},
				{src:null,img:'https://ym-a.top/wx/img/tu1.jpg',address:'func/red.html'},
				{src:null,img:'https://ym-a.top/wx/img/tu1.jpg',address:'func/red.html'},
			]
		},
		verifyData:{
			verify:true,
			showModule:false,
			cell:{
				a:true,
				b:true,
				c:true,
				d:true,
				e:true,
				f:true,
				g:true,
				h:true,
				i:true,
			}
		},
		fastTrackData:{
			showModule:false,
			fastTrack:false,
			website:true,
			websiteVal:'微官网',
			officialAccounts:true,
			officialAccountsVal:'查看公众号',
			complain:true,
			complainVal:'投诉反馈',
			weiStore:true,
			weiStoreVal:'官方微商城'
		},
		continueData:{
			continue:false,
		},
		promotionVedioData:{
			promotionVedio:false,
			showModule:false,
			title:'宣传视频',
			videoSrc:null
		},
		couponData: {
			coupon:true,
		}
	},
	mutations:{
		reset(state){
			state.isNew=true,
			state.actionId=null,
			state.vendorId=null,
			state.data={
				picAd1:false,
				showModule:false,
				picNum:2,
				bannerPic:[
				{src:null,img:'https://ym-a.top/wx/img/tu2.jpg',address:'func/you.html'},
				{src:null,img:'https://ym-a.top/wx/img/tu1.jpg',address:'func/red.html'},
				{src:null,img:'https://ym-a.top/wx/img/tu1.jpg',address:'func/red.html'},
				]
			};
			state.verifyData={
				verify:true,
				showModule:false,
				cell:{
					a:true,
					b:true,
					c:true,
					d:true,
					e:true,
					f:true,
					g:true,
					h:true,
					i:true,
				}
			};
			state.fastTrackData={
				showModule:false,
				fastTrack:false,
				website:true,
				websiteVal:'微官网',
				officialAccounts:true,
				officialAccountsVal:'查看公众号',
				complain:true,
				complainVal:'投诉反馈',
				weiStore:true,
				weiStoreVal:'官方微商城'
			};
			state.continueData.continue=false;
			state.promotionVedioData={
				promotionVedio:false,
				showModule:false,
				title:'宣传视频',
				videoSrc:null
			};
		},
		compile(state,data){
			state.continueData=data.continueData;
			state.couponData=data.couponData;
			state.data=data.data;
			state.fastTrackData=data.fastTrackData;
			state.isNew=data.isNew;
			state.promotionVedioData=data.promotionVedioData;
			state.verifyData=data.verifyData;
			state.actionId=data.actionId;
			state.vendorId=data.vendorId;
		},
		showPicAd1(state){
			console.log(state)
			state.data.picAd1=true;
		},
		delThis1(state){
			state.data.picAd1=false;
			state.data.showModule=false;
		},
		delThis2(state){
			state.verifyData.verify=false;
			state.verifyData.showModule=false;
		},
		delThis3(state){
			state.fastTrackData.fastTrack=false;
			state.fastTrackData.showModule=false;
		},
		delThis4(state){
			state.continueData.continue=false;
		},
		delThis5(state){
			state.promotionVedioData.showModule=false;
			state.promotionVedioData.promotionVedio=false;
		},
		delThis6(state){
			state.couponData.coupon=false;
		},
		module(state,type){
			if(type=='picAd1'){
				state.verifyData.showModule=false;
				state.fastTrackData.showModule=false;
				state.promotionVedioData.showModule=false;
				state.data.showModule=true;
			}
			if(type=='verify'){
				state.data.showModule=false;
				state.verifyData.showModule=true;
				state.promotionVedioData.showModule=false;
				state.fastTrackData.showModule=false;
			}
			if(type=='fastTrack'){
				state.data.showModule=false;
				state.verifyData.showModule=false;
				state.promotionVedioData.showModule=false;
				state.fastTrackData.showModule=true;
			}
			if(type=='promotionVedio'){
				state.data.showModule=false;
				state.verifyData.showModule=false;
				state.fastTrackData.showModule=false;
				state.promotionVedioData.showModule=true;
			}
		},
		addPicNum(state){
			if(state.data.picNum<=4){
				state.data.picNum++;
			}
		},
		setPic(state,data){
			if(data.type===1){
				state.data.bannerPic[0].src=data.url;
			}
			if(data.type===2){
				state.data.bannerPic[1].src=data.url;
			}
			if(data.type===3){
				state.data.bannerPic[2].src=data.url;
			}
		},
		addVerify(state){
			if(!state.verifyData.verify){
				state.verifyData.verify=true;
			}
		},
		addFastTrack(state){
			if(!state.fastTrackData.fastTrack){
				state.fastTrackData.fastTrack=true;
			}
		},
		addContinue(state){
			if(!state.continueData.continue){
				state.continueData.continue=true;
			}
		},
		addPromotionVedio(state){
			if(!state.promotionVedioData.promotionVedio){
				state.promotionVedioData.promotionVedio=true;
			}
		},
		addCoupon(state){
			if(!state.couponData.coupon){
				state.couponData.coupon=true;
			}
		},
		updateMessage(state,type){
			if(type==='a'){
				state.verifyData.cell.a=!state.verifyData.cell.a
			}
			if(type==='b'){
				state.verifyData.cell.b=!state.verifyData.cell.b
			}
			if(type==='c'){
				state.verifyData.cell.c=!state.verifyData.cell.c
			}
			if(type==='d'){
				state.verifyData.cell.d=!state.verifyData.cell.d
			}
			if(type==='f'){
				state.verifyData.cell.f=!state.verifyData.cell.f
			}
			if(type==='g'){
				state.verifyData.cell.g=!state.verifyData.cell.g
			}
			if(type==='h'){
				state.verifyData.cell.h=!state.verifyData.cell.h
			}
			if(type==='i'){
				state.verifyData.cell.i=!state.verifyData.cell.i
			}
			if(type==='website'){
				state.fastTrackData.website=!state.fastTrackData.website
			}

			if(type==='officialAccounts'){
				state.fastTrackData.officialAccounts=!state.fastTrackData.officialAccounts
			}
			if(type==='complain'){
				state.fastTrackData.complain=!state.fastTrackData.complain
			}
			if(type==='weiStore'){
				state.fastTrackData.weiStore=!state.fastTrackData.weiStore
			}
		},
		changeVal(state,obj){
			if(obj.type==='website'){
				state.fastTrackData.websiteVal=obj.value;
			}
			if(obj.type==='officialAccounts'){
				state.fastTrackData.officialAccountsVal=obj.value;
			}
			if(obj.type==='complain'){
				state.fastTrackData.complainVal=obj.value;
			}
			if(obj.type==='weiStore'){
				state.fastTrackData.weiStoreVal=obj.value;
			}
			if(obj.type==='title'){
				state.promotionVedioData.title=obj.value;
			}
			if(obj.type==='videoSrc'){
				state.promotionVedioData.videoSrc=obj.value;
			}
			if(obj.type==='bannerPic0'){
				state.data.bannerPic[0].address=obj.value;
			}
			if(obj.type==='bannerPic1'){
				state.data.bannerPic[1].address=obj.value;
			}
			if(obj.type==='bannerPic2'){
				state.data.bannerPic[2].address=obj.value;
			}
		}
	},
	actions:{
		showPicAd1(context){
			context.commit('showPicAd1');
		},
		delThis1(context){
			context.commit('delThis1')
		},
		module(context,type){
			context.commit('module',type)
		},
		setPic(context,data){
			context.commit('setPic',data)
		},
		addPicNum(context){
			context.commit('addPicNum')
		},
		addVerify(context){
			context.commit('addVerify');
		}
	}
}
const store = new Vuex.Store({
	modules: {
		a:picAd,
		b:codeType,
		c:gameRule,
		banner1:banner1,
	}
})

export default store
